# This is a basic workflow to help you get started with Actions

name: Python Package

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: Ubuntu-latest
    strategy:
      matrix:
        python-version: [3.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flask
          pip install flask-sqlalchemy
